---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: BlueXPデジタルウォレットを使用すると、ネットアップ（BYOL）、BlueXPマーケットプレイスのサブスクリプション、NetApp Keystone から購入したBlueXPライセンスを管理、監視できます。 
---
= BlueXPのデジタルウォレットの詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  デジタルウォレットを使用すると、NetApp（BYOL）、BlueXP  データサービスマーケットプレイスのサブスクリプション（NetApp Cloud Volumes ONTAPを含む）、NetApp Keystoneから購入したBlueXP  ライセンスを管理および監視できます。



== デジタルウォレットでのライセンスとサブスクリプションの表示方法

サブスクリプションに使用したBlueXP  アカウントがNetAppサポートサイトのアカウントでもある場合、ライセンスとサブスクリプションの両方がデジタルウォレットに自動的に表示されます。NetAppサポートサイト（NSS）のアカウントに関連付けられていないBlueXP  アカウントを使用していた場合は、ライセンスを手動で追加および更新する必要があります。使用状況、容量、その他の詳細は変更されません。

一方、BlueXPは、ネットアップのライセンスサービスに自動的に問い合わせて、NetApp Support Site アカウントに関連付けられているライセンスの詳細を取得します。エラーがなければ、BlueXPは自動的にライセンスをデジタルウォレットに追加します。

BlueXP  がライセンスを追加できない場合は、手動でデジタルウォレットに追加する必要があります。たとえば、BlueXP  ユーザアカウントがNetAppサポートサイトのアカウントに関連付けられていない場合は、自分でライセンスを追加する必要があります。

NetAppの営業担当者からライセンスを購入すると、シリアル番号と追加ライセンスの詳細が記載されたEメールがNetAppから送信されます。デジタルウォレットのそれぞれのライセンスを追加または更新するには、そのシリアル番号が必要です。

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["NetAppサポートサイトのアカウントをBlueXP  のユーザクレデンシャルに追加する方法"^]です。



== サポートされるサービス

BlueXP  デジタルウォレットを使用すると、次のサービスのライセンスとサブスクリプションを管理できます。

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["バックアップとリカバリ"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["ディザスタリカバリ"^] （BYOLのみ）
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["ランサムウェア対策"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["オンプレミスの ONTAP クラスタ"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["階層化"^]

