---
settings:
  name: BlueXP digital wallet
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXPデジタルウォレットドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: BlueXPのデジタルウォレットの詳細をご確認ください
      url: "/concept-digital-wallet.html"
  - title: BlueXPのデジタルウォレットをご利用ください
    entries:
    - title: 概要ダッシュボードの使用
      url: "/task-homepage.html"
    - title: ライセンスの管理
      entries:
      - title: 直接ライセンスの管理
        url: "/task-manage-data-services-licenses.html"
      - title: Cloud Volumes ONTAP のライセンスを管理します
        entries:
        - title: Cloud Volumes ONTAPヨウリヨウヘエスライセンス
          url: "/task-manage-capacity-licenses.html"
        - title: Cloud Volumes ONTAPノノオトヘエスライセンス
          url: "/task-manage-node-based-licenses.html"
    - title: プライベートオファーを管理する
      entries:
      - title: BlueXPの AWS プライベートオファーを管理する
        url: "/task-manage-private-aws.html"
      - title: BlueXPの Azure プライベート オファーを管理する
        url: "/task-manage-private-azure.html"
      - title: NetApp BlueXP向け Google Cloud プライベート オファーを管理する
        url: "/task-manage-private-google-cloud.html"
    - title: Marketplaceサブスクリプションの管理
      url: "/task-manage-subscriptions.html"
    - title: Keystoneサブスクリプションを管理
      url: "/task-manage-keystone.html"
    - title: オンプレミスのONTAPのライセンスを管理
      url: "/task-manage-on-prem-clusters.html"
    - title: 知識とサポート
      entries:
      - title: サポートに登録します
        url: "/task-support-registration.html"
      - title: ヘルプを表示します
        url: "/task-get-help.html"
    - title: 法的通知
      url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
