---
sidebar: sidebar 
permalink: task-manage-private-aws-cloud-insights.html 
keywords: activate,license, licensing, install, request capacity, link subscription, digital wallet, keystone flex, digital wallet, bluexp digital wallet 
summary: AWS、Azure、Google Cloud 向けの、一般的な、ハイパースケーラー固有の、エンドツーエンドのプライベート オファー プロセスと、 NetAppインテリジェント サービスの承認およびアクティベーション ガイドを管理します。 
---
= NetApp Cloud Insightsの AWS Marketplace プライベートオファーを承認して設定する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AWS コンソールでNetApp Cloud Insightsの Marketplace プライベートオファーを承認します。  AWS サブスクリプションをCloud Insights作業環境に接続します。

.作業を開始する前に
* NetApp の営業担当者と協力してプライベート オファーを作成し、オファー リンクを取得します。
* NetApp の営業担当者と協力してCloud Insights の作業環境を作成し、*オーナー* ロールを持つメールを追加します。
* 必要なものがあることを確認してくださいlink:https://docs.aws.amazon.com/marketplace/latest/buyerguide/buyer-iam-users-groupspolicies.html["AWS マーケットプレイスの権限"]




== AWSコンソールでプライベートオファーを承認する

[IMPORTANT]
====
プライベートオファーを有効にするには、すべての手順を完了する必要があります。手順を省略すると、アクティベーションの問題や二重請求などの請求エラーが発生する可能性があります。

====
.手順
. NetApp の営業チームから提供されたプライベート オファーのアクティベーション リンクをクリックします。リンクは次のようになります。
`https://aws.amazon.com/marketplace/saas/ordering?productId=aaa&offerId=offer-aaa`
+
[NOTE]
====
アクティベーションリンクを受け取っていない場合は、AWS コンソールですべてのプライベートオファーを表示できます。

** 必要な管理ポリシー: *AWSMarketplaceRead-only*、*AWSMarketplaceManageSubscriptions*、または *AWSMarketplaceFullAccess*
** カスタム IAM ポリシーを使用する場合: `aws-marketplace:ListPrivateListings`そして `aws-marketplace:ViewSubscriptions`


====
. プライベートオファーを表示して承認するために、AWS Marketplace にリダイレクトされます。
+
[NOTE]
====
プライベートオファーは公開リストの上に作成されます。  *オファーの選択*ドロップダウンを使用して、公開オファーと非公開オファーを切り替えます。

====
. プライベートオファーの詳細を確認し、契約内容と一致していることを確認します。
+
.. 情報が間違っている場合は、受け入れないでください。オファーを修正するには、 NetAppの営業チームにお問い合わせください。
.. *サブスクライブ*を選択すると課金が開始されます。
+
[NOTE]
====
AWS には 2 つのプライベートオファータイプが存在します。

*** *オンデマンド利用*
+
**** 価格情報
**** 法的用語


*** *契約*
+
**** 期間と日付
**** 更新設定
**** 契約オプション
**** 契約合計金額




契約オファーの場合は、合意された管理対象ユニットの数を入力します。

====


. プライベートオファーを承諾するには:
+
.. オンデマンドで使用する場合は、「*サブスクライブ*」をクリックします。
.. 契約オファーの場合は、各サービスの管理対象ユニット数を入力し、「契約を作成」をクリックします。


. 承認されると、バナーが表示され、正常に登録されたことが確認され、次の手順が示されます。
. *アカウントを設定*をクリックします。これにより、 NetApp Cloud Insightsにリダイレクトされ、Marketplace サブスクリプションが構成されます。
+
[NOTE]
====
オファーが受け入れられたが登録が完了していない場合は、製品ページに戻ります。登録を完了するように求められます。

契約オファーの場合は、「*購入オプションを表示*」をクリックしてプライベートオファーを表示し、「*アカウントを設定*」を選択します。

====




== サブスクリプションをCloud Insightsに接続する

.手順
. リダイレクトされます https://cloudinsights.netapp.com[]BlueXPアカウントでサインインするように求められます。
. *オーナー* ロールを持つアカウントでログインします。サブスクリプションは、 Cloud Insightsの作業環境に関連付けられます。
+
[NOTE]
====
この手順は、サブスクリプションごとに 1 回だけ必要です。更新とアドオンは自動的に適用されます。

====
. サブスクリプションが接続されました。

